-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-12-06 16:50:22 CET
--   site:      SQL Server 2008
--   type:      SQL Server 2008



CREATE TABLE archeolog (
    aid             INTEGER IDENTITY NOT NULL,
    jmeno           VARCHAR(30),
    prijmeni        VARCHAR(30),
    mobilni_cislo   INTEGER NOT NULL,
    email           VARCHAR(40),
    CONSTRAINT check_at_sign1 CHECK(email like '%@%'),
    CONSTRAINT check_telephone_number1
    CHECK (mobilni_cislo BETWEEN 100000000 AND 1000000000)
);


ALTER TABLE Archeolog ADD constraint archeolog_pk PRIMARY KEY CLUSTERED (aID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE artefakt (
    aid                             INTEGER IDENTITY NOT NULL,
    nazev                           VARCHAR(30) NOT NULL,
    datum_nalezeni                  datetime NOT NULL,
    odhadovane_stari_artefaktu      INTEGER,
    zeme_nalezu                     VARCHAR(40) NOT NULL,
    zeme_puvodu_artefaktu           VARCHAR(50),
    gps_souradnice_nalezu           bigint,
    popis                           text,
    datum_vystaveni                 datetime,
    je_prozkouman_a_zdokumentovan   bit NOT NULL,
    datum_posledni_kontroly         datetime,
    vypujceno_od                    VARCHAR(100),
    propujceno_muzeu                VARCHAR(100),
    archeolog_aid                   INTEGER NOT NULL
);


ALTER TABLE Artefakt ADD constraint artefakt_pk PRIMARY KEY CLUSTERED (aID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE navsteva (
    nid                  INTEGER IDENTITY NOT NULL,
    pocet_osob           INTEGER NOT NULL,
    datum_cas_navstevy   datetime NOT NULL,
    rezervace_rid        INTEGER NULL,
    recepce_rid          INTEGER NOT NULL,
    vystava_vid          INTEGER NOT NULL
);



ALTER TABLE Navsteva ADD constraint navsteva_pk PRIMARY KEY CLUSTERED (nID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE pruvodce (
    pid             INTEGER IDENTITY NOT NULL,
    jmeno           VARCHAR(24) NOT NULL,
    prijmeni        VARCHAR(24) NOT NULL,
    mobilni_cislo   INTEGER,
    CONSTRAINT check_telephone_number2
    CHECK (mobilni_cislo BETWEEN 100000000 AND 1000000000)
);


ALTER TABLE Pruvodce ADD constraint pruvodce_pk PRIMARY KEY CLUSTERED (pID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE recepce (
    rid             INTEGER IDENTITY NOT NULL,
    jmeno           VARCHAR(24) NOT NULL,
    prijmeni        VARCHAR(24) NOT NULL,
    email           VARCHAR(50),
    mobilni_cislo   INTEGER NOT NULL,
    CONSTRAINT check_at_sign2 CHECK(email like '%@%'),
    CONSTRAINT check_telephone_number3
    CHECK (mobilni_cislo BETWEEN 100000000 AND 1000000000)
);


ALTER TABLE Recepce ADD constraint recepce_pk PRIMARY KEY CLUSTERED (rID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE rezervace (
    rid                   INTEGER IDENTITY NOT NULL,
    jmeno                 VARCHAR(24) NOT NULL,
    prijmeni              VARCHAR(24) NOT NULL,
    pocet_osob            INTEGER NOT NULL,
    zarezervovane_datum   datetime NOT NULL,
    datum_vytvoreni       datetime NOT NULL,
    pruvodce_pid          INTEGER NOT NULL,
    CONSTRAINT check_max_people
    CHECK (pocet_osob BETWEEN 1 AND 30)
);


ALTER TABLE Rezervace ADD constraint rezervace_pk PRIMARY KEY CLUSTERED (rID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE vystava 
    (
    vid             INTEGER IDENTITY NOT NULL,
    popis_vystavy   varchar
(max), datum_zacatku_vystavy datetime, datum_konce_vystavy datetime,
    UNIQUE (vid) );


ALTER TABLE Vystava ADD constraint vystava_pk PRIMARY KEY CLUSTERED (vID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE vystavene_artefakty (
    artefakt_aid   INTEGER NOT NULL,
    vystava_vid    INTEGER NOT NULL
);


CREATE TABLE zmena_rezervace (
    zrid                      INTEGER IDENTITY NOT NULL,
    datum_puvodni_rezervace   datetime NOT NULL,
    datum_nove_rezervace      datetime NOT NULL,
    datum_zmeny               datetime NOT NULL,
    rezervace_rid             INTEGER NOT NULL
);


ALTER TABLE Zmena_rezervace ADD constraint zmena_rezervace_pk PRIMARY KEY CLUSTERED (zrID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

ALTER TABLE Artefakt
    ADD CONSTRAINT artefakt_archeolog_fk FOREIGN KEY ( archeolog_aid )
        REFERENCES archeolog ( aid )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE Navsteva
    ADD CONSTRAINT navsteva_recepce_fk FOREIGN KEY ( recepce_rid )
        REFERENCES recepce ( rid )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE Navsteva
    ADD CONSTRAINT navsteva_rezervace_fk FOREIGN KEY ( rezervace_rid )
        REFERENCES rezervace ( rid )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE Navsteva
    ADD CONSTRAINT navsteva_vystava_fk FOREIGN KEY ( vystava_vid )
        REFERENCES vystava ( vid )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE Rezervace
    ADD CONSTRAINT rezervace_pruvodce_fk FOREIGN KEY ( pruvodce_pid )
        REFERENCES pruvodce ( pid )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE Vystavene_artefakty
    ADD CONSTRAINT vystavene_artefakty_artefakt_fk FOREIGN KEY ( artefakt_aid )
        REFERENCES artefakt ( aid )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE Vystavene_artefakty
    ADD CONSTRAINT vystavene_artefakty_vystava_fk FOREIGN KEY ( vystava_vid )
        REFERENCES vystava ( vid )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE Zmena_rezervace
    ADD CONSTRAINT zmena_rezervace_rezervace_fk FOREIGN KEY ( rezervace_rid )
        REFERENCES rezervace ( rid )
ON DELETE NO ACTION 
    ON UPDATE no action;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             1
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
